change ssh-action version

diff --git a/.github/workflows/deploy_client-ms.yml b/.github/workflows/deploy_client-ms.yml
--- a/.github/workflows/deploy_client-ms.yml
+++ b/.github/workflows/deploy_client-ms.yml
@@ -43,3 +43,21 @@ jobs:
       VPS_USERNAME: ${{ secrets.VPS_USERNAME_INTERNAL }}
       VPS_PASSWORD: ${{ secrets.VPS_PASSWORD_INTERNAL }}
       SECRET_PASSWORD: ${{ secrets.SECRET_PASSWORD }}
+
+  healthcheck:
+    needs: [deploy]
+    uses: appleboy/ssh-action@v2 
+    env: 
+      SERVER_PORT: 8001 
+    with: 
+      VPS_HOST: ${{ secrets.VPS_HOST_INTERNAL }} 
+      VPS_USERNAME: ${{ secrets.VPS_USERNAME_INTERNAL }} 
+      VPS_PASSWORD: ${{ secrets.VPS_PASSWORD_INTERNAL }} 
+      SCRIPT: |
+        script_output=$(bash /root/healthchecks/healthcheck-script.sh $SERVER_PORT) 
+        echo "$script_output" 
+        if [ $? -eq 0 ]; then 
+          echo "::set-output name=status::success" 
+        else 
+          echo "::set-output name=status::failure" 
+        fi
